export const ProfileKey = {
  FirstName: 'firstName',
  LastName: 'lastName',
  FullName: 'fullName',
  Email: 'email',
  Phone: 'phone',
  PhoneCountryCode: 'phoneCountryCode',
  AddressLine1: 'addressLine1',
  AddressLine2: 'addressLine2',
  City: 'city',
  State: 'state',
  PostalCode: 'postalCode',
  Country: 'country',
  LinkedinUrl: 'linkedinUrl',
  GithubUrl: 'githubUrl',
  PortfolioUrl: 'portfolioUrl',
  WorkAuthorization: 'workAuthorization',
  RequiresSponsorship: 'requiresSponsorship',
  YearsExperience: 'yearsExperience',
  CurrentTitle: 'currentTitle',
  CurrentCompany: 'currentCompany',
  DesiredSalary: 'desiredSalary',
  AvailableStartDate: 'availableStartDate',
  NoticePeriod: 'noticePeriod',
  EeoAge: 'eeoAge',
  EeoGender: 'eeoGender',
  EeoEthnicity: 'eeoEthnicity',
  EeoCommunities: 'eeoCommunities',
  EeoVeteranStatus: 'eeoVeteranStatus',
  EeoDisabilityStatus: 'eeoDisabilityStatus',
  Resume: 'resume',
} as const;

export type ProfileKey = (typeof ProfileKey)[keyof typeof ProfileKey];

export const ALL_PROFILE_KEYS: ProfileKey[] = Object.values(ProfileKey);
